variables:
  PIP_CACHE_DIR: "$CI_BUILDS_DIR/$CI_PROJECT_NAME/.cache/pip"
  GITLAB_PYTHON_VERSION: python:3.11
  GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_PROJECT_NAME/$CI_PIPELINE_ID'

stages:
  - lint
  - test

cache:
  paths:
    - .cache/pip
    - venv/

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: "Jobs/Secret-Detection.latest.gitlab-ci.yml"
  - template: "Security/Dependency-Scanning.gitlab-ci.yml"
  - template: "Security/License-Scanning.gitlab-ci.yml"
  - project: 'smartdcs1/internal/gitlab-ci-templates/python-linting-ci'
    ref: main
    file: '.python-linting-ci-template.yml'
  - '/ci/.terraform-ci.yml'

pytest:
  image: $GITLAB_PYTHON_VERSION
  stage: test
  before_script:
    - pip install pytest
    - pytest --version
    - pip install -r requirements.txt
    - ./ci/install_prerequisites.sh
  script:
    - export PYTHONPATH=/workspaces/test-harness:$PYTHONPATH
    - pytest --junitxml=report.xml --ignore=tests/test_harness/protocol_verifier/test_pvresultsdaskdataframe.py

  artifacts:
    when: always
    reports:
      junit: report.xml
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'