version: "1"
name: test-harness-dev
services:
  test-harness:
    build: 
      dockerfile: ./Dockerfile
      ssh: 
        - default
    volumes:
      - "./config:/config"
      - "./report_output:/test_harness_app/test_harness/report_output"
      - "./uml_file_store:/test_harness_app/test_harness/uml_file_store"
    ports:
    - 8800:8800
