swagger: '2.0'
info:
  version: 1.0.0
  title: Minos Public API
  description: Central API for Minos stack
schemes: 
- https
produces:
    - application/json
basePath: /api/v1
paths:
  /projects:
    get:
      description: Get all projects
      tags:
        - "projects"
      produces:
        - "application/json"
      responses:
        200:
          description: Successfully returned a list of projects 
          schema:
            type: string
          examples:
            projects: 'my example'