@startuml deployment
cloud VPC {
    actor User
    node "PV Server" as EC2PV {
        port "Message Bus Port" as PVMBusPort
        port "Metrics Port" as PVMetricsPort
        folder "Job\nDefintions" as JDEF
        folder "Reception\nIncoming" as AER_INC
        folder "Logs\nReception" as LOG_F_AER
        folder "Logs\nVerifier" as LOG_F_VER
        folder "Job Id\nStore" as ID_STORE
        folder "Invariant\nStore" as INV_STORE
        component "Protocol\nVerifier" as PV
        component "HTTP Server" as HTTP {
            portin "9000" as HTTP_9000
        }
    }
    node "Metrics Collection" as Metrics {
        port "port" as MetricsPortin
        portout "port" as MetricsPortOut
    }
    node "Message Bus" as MBus {
        port "port" as MBusPortin
        portout "port" as MBusPortout
    }
    node "Test Harness Server" as EC2Harness {
        port "8800" as ec2_8800
        component "Test Harness Container" as TH {
            portin "8800" as TH_8800
            portout "port" as TH_Dynamic
            portout "port" as TH_Dynamic_message
            portout "port" as TH_Dynamic_metrics
        }
    }
}
ec2_8800 --> TH_8800 : Forward HTTP Requests
User --> ec2_8800 : Send HTTP Requests
TH_Dynamic --> HTTP_9000 : Send HTTP\nserver\nRequests
TH_Dynamic_message --> MBusPortin : Send Message\nBus Requests
MBusPortout --> PVMBusPort : Forward\nmessages
TH_Dynamic_metrics <--> MetricsPortin : Request metrics
MetricsPortOut <--> PVMetricsPort : Get Metrics

HTTP --> JDEF : Mounted
HTTP --> AER_INC : Mounted
HTTP --> LOG_F_AER : Mounted
HTTP --> LOG_F_VER : Mounted
HTTP --> ID_STORE : Mounted
HTTP --> INV_STORE : Mounted
@enduml