version: "1"
name: test-harness
services:
  test-harness:
    image: "registry.gitlab.com/smartdcs1/cdsdt/test-harness:MuninP2S1-midstage"
    volumes:
      - "./config:/config"
      - "./report_output:/test_harness_app/test_harness/report_output"
      - "./uml_file_store:/test_harness_app/test_harness/uml_file_store"
    ports:
    - 8800:8800