@startuml
participant Client as "Client"
participant HTTP as "HTTP Server"
database LogFiles as "Mounted Logs\nFolder"
Client -> HTTP : POST request\n with log file name
HTTP <-> LogFiles : Check log file name exists
alt file exists
    HTTP -> Client : Send log file
else file does not exist
    HTTP -> Client : Send 400 response
end 
@enduml