@startuml
#green:A;
:B;
repeat
    fork
        :C;
    fork again
        :D;
    end fork
    :E;
    if (XOR) then (true)
        :F;
    else (false)
        :G;
    endif
repeat while (loop)
#red:H;
@enduml