@startuml
left to right direction
file "PlantUML\nActivity\nDiagram" as PUML
    component "Test Harness" as TH {
    component "Test\nEvent\nGenerator" as TEG
    component "Plus2JSON" as PJ
    frame "Event Sequences" as EventSEQ{
        folder "Valid" as Valid
        folder "Invalid" as Invalid
    }
    file "Protocol\nVerifier\nConfig" as Config
    component "Protocol\nVerifier" as PV
    file "Logs" as LOG
    component "Check Pass/Fail" as CHECK
}
file "Passes" as Pass
file "Failures" as Fail

PUML --> TEG
PUML --> PJ
TEG --> EventSEQ
PJ --> Config
EventSEQ --> PV
Config --> PV
PV --> LOG
LOG --> CHECK
CHECK --> Pass
CHECK --> Fail

@enduml