cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .terraform

variables:
  GL_ASDF_TFLINT_VERSION: "0.41.0"
  GL_ASDF_TERRAFORM_VERSION: "1.3.7"
  # Exclude vendor and files directories from validation
  COMMON_TASK_VALIDATIONS_EXCLUDES_REGEXP: '^\.(/vendor/|/files/|/examples)'

tfsec:
  stage: lint
  image: 
    name: tfsec/tfsec-ci:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - tfsec -f junit --out tfsec.test
  artifacts:
    paths:
      - tfsec.test
    reports:
      junit: "tfsec.test"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - changes:
      - "*.{tf}"

tflint:
  stage: lint
  needs: []
  image:
    name: registry.gitlab.com/gitlab-com/gl-infra/common-ci-tasks-images/tflint:${GL_ASDF_TFLINT_VERSION}
    entrypoint: [""]
  script:
    - mkdir -p "tflint-reports/"
    # Find all TF files and lint the directories of those files
    - tflint --init -c .tflint.hcl
    # Loop through all the directories containing *.tf files and run tflint in them
    - find . -type f -name '*.tf' | grep -vE "${COMMON_TASK_VALIDATIONS_EXCLUDES_REGEXP:-__ignored__}" | sed -e 's#/[^/]*$##' | sort -u | grep -v "${TFLINT_EXCLUDE_REGEX:-__ignored__}" | while read -r dir; do
        junit_file="$(echo "$dir"|sed -r 's/[^a-zA-Z0-9]+/-/g' | sed -r s/^-+\|-+$//g).xml";
        echo "${dir} -------------------------------------------------------";
        cd "${CI_PROJECT_DIR}/${dir}" || exit 1;
        terraform init -backend=false -reconfigure;
        tflint -c "${CI_PROJECT_DIR}/.tflint.hcl" . -f compact || echo "${dir}" >> "${CI_PROJECT_DIR}/tflint-reports/failed";
        tflint -c "${CI_PROJECT_DIR}/.tflint.hcl" . -f junit > "${CI_PROJECT_DIR}/tflint-reports/${junit_file}";
      done;
    # tflint-reports/failed indicates a linter failure
    - if [ -f "${CI_PROJECT_DIR}/tflint-reports/failed" ]; then
        echo "Failures found in:";
        cat "${CI_PROJECT_DIR}/tflint-reports/failed";
        exit 1;
      fi
  artifacts:
    when: always
    reports:
      junit: tflint-reports/**
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - changes:
      - "*.{tf}"
