- name: Read-write git checkout for required repos and build test harness
  hosts: test_harness
  become: true
  become_user: "{{ ansible_ssh_user }}"
  gather_facts: false
  tasks:
    - name: Ensure git keys are sent to github and gitlab
      shell: |
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts

    - name: Clone test-harness repo
      ansible.builtin.git:
        repo: git@github.com:SmartDCSITlimited/test-harness.git
        dest: ~/test-harness
    
    - name: Clone data-scripts repo
      ansible.builtin.git:
        repo: git@gitlab.com:smartdcs1/cdsdt/data-scripts.git
        dest: ~/data-scripts
  
    - name: Build Test Harness
      shell: |
        cd ~/test-harness
        docker build -t test-harness:latest --ssh default .
