---
- name: Install docker on alma linux test harness box
  hosts: test_harness
  gather_facts: false
  become: true
  tasks:
    - name: Upgrade all packages on servers
      dnf:
        name: '*'
        state: latest

    - name: Uninstall old versions
      dnf:
        name:
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent

    - name: Set up docker repository
      shell: |
        dnf install -y yum-utils
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      # args:
      #   warn: false

    - name: Install the latest version of Docker Engine and containerd
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify: Start and enable docker

    - name: Add the current user to the docker group
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes
    
    
    

  handlers:
    - name: Start and enable docker
      systemd:
        name: docker
        state: started
        enabled: yes


- name: Install git on alma linux test harness box
  hosts: test_harness
  gather_facts: false
  become: true
  tasks:
    - name: Install the latest version of git
      dnf:
        name: git
        state: latest