name: End-to-End Test

on:
  push:
    branches:
      ## TODO consider whether this should be on all commits or just on PRs (depending on speed)
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitLab Docker registry
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and run containers
      #   uses: adambirds/docker-compose-action@v1.3.0
      #   with:
      #     compose-file: ./docker-compose-end-to-end-test.yml

      - name: Build and run containers
        run: |
          docker compose -f ./docker-compose-end-to-end-test.yml pull
          docker compose -f ./docker-compose-end-to-end-test.yml up -d

          # sudo docker compose --progress plain -f ./docker-compose-end-to-end-test.yml up -d

      - name: Run curl commands
        run: |
          sleep 1
          echo "you made it!"
          curl --location --request POST 'http://127.0.0.1:8800/uploadUML' --form 'file1=@"./tests/test_harness/test_files/test_uml_1.puml"'
          curl -X POST -d '{"TestName": "demo4", "TestConfig":{"event_gen_options":{"invalid":false}, "type":"Performance", "performance_options": {"num_files_per_sec":10, "total_jobs":100, "shard":true}}}' -H 'Content-Type: application/json' 'http://127.0.0.1:8800/startTest'

          docker compose -f ./docker-compose-end-to-end-test.yml logs test-harness
          docker compose -f ./docker-compose-end-to-end-test.yml down
