name: End-to-End Test

on:
  push:
    branches:
      ## TODO consider whether this should be on all commits or just on PRs (depending on speed)
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitLab Docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Build and run containers
        run: |
          docker-compose up -d -f .github/workflows/docker-compose.yml

      - name: Run curl commands
        run: |
          sleep 1
          echo "you made it!"
          # Add your curl commands here
