name: End-to-End Test

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      'main'

jobs:
  build-and-test:
    if: |
        github.repository == 'xtuml/erebus'
            && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Create Docker network
        run: docker network create my-network

      - name: Do test
        run: |
          # Pull munin repo from https://github.com/xtuml/munin.git
          git clone https://github.com/xtuml/munin.git

          # Checkout to tags/1.3.1-midstage3
          cd munin
          git checkout tags/1.3.1-midstage3

          # Change to root directory
          cd ..

          # Replace munin/deploy/config/log-pv-files.properties with ./end_to_end_test_files/log-pv-files.properties
          cp ./end_to_end_test_files/log-pv-files.properties ./munin/deploy/config/log-pv-files.properties

          # Replace munin/deploy/config/log-pv-kafka.properties with ./end_to_end_test_files/log-pv-kafka.properties
          cp ./end_to_end_test_files/log-pv-kafka.properties ./munin/deploy/config/log-pv-kafka.properties

          # Replace munin/deploy/docker-compose.prod.yml
          cp ./end_to_end_test_files/docker-compose.prod.yml ./munin/deploy/docker-compose.prod.yml

          # Run docker compose up -f docker-compose.prod.yml up
          docker compose -f ./munin/deploy/docker-compose.prod.yml up -d

          # Copy config.config file
          mkdir -p config
          cp ./end_to_end_test_files/config.config ./config/config.config
          # sed -i 's/host\.docker\.internal/http_server/g' ./config/config.config

          docker compose -f ./docker-compose-end-to-end-test.yml up -d

          # this should return false as no tests are running
          sleep 10
          echo "Testing that no tests are running"
          curl 127.0.0.1:8800/isTestRunning | grep 'false'

          # actual tests are set to run
          # timeout 2m ./scripts/end-to-end-curl-commands.sh
          timeout 1m ./scripts/end-to-end-curl-commands.sh

          # this should return true as tests are running
          echo "Testing that tests are running"
          echo `curl 127.0.0.1:8800/isTestRunning`
          sleep 30
          echo `curl 127.0.0.1:8800/isTestRunning`
          sleep 30
          echo `curl 127.0.0.1:8800/isTestRunning`
          sleep 30
          echo `curl 127.0.0.1:8800/isTestRunning`
          sleep 30
          curl 127.0.0.1:8800/isTestRunning | grep 'true'

          # It takes this long to get any meaningful output from the test harness
          # It's 60 seconds for the test harness to start the job ...
          # ... and 10 seconds to run the job ...
          # ... and 60 seconds to ensure the test is finished ...
          # ... and another 50 seconds for grace time in starting up/waiting for logs/waiting for calculations
          echo "Sleeping to give the test harness time to work"
          date
          sleep 60
          echo "Testing that a percentage is returned"
          curl 127.0.0.1:8800/isTestRunning | grep percent_done
          date
          sleep 30
          echo `curl 127.0.0.1:8800/isTestRunning`
          sleep 30
          echo `curl 127.0.0.1:8800/isTestRunning`
          sleep 30
          echo `curl 127.0.0.1:8800/isTestRunning`
          sleep 30
          echo `curl 127.0.0.1:8800/isTestRunning`
          sleep 30
          echo `curl 127.0.0.1:8800/isTestRunning`
          sleep 30
          echo `curl 127.0.0.1:8800/isTestRunning`
          sleep 30
          echo `curl 127.0.0.1:8800/isTestRunning`

          docker compose -f ./docker-compose-end-to-end-test.yml logs test-harness | grep -Po "Test Harness test run completed successfully"
          docker compose -f ./docker-compose-end-to-end-test.yml down


      # - name: Save the whole repo to know exactly what happened in there
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: whole-repo
      #     path: |
      #       **/*
      #       !/home/runner/work/test-harness/test-harness/$SSH_AUTH_SOCK