name: install_requirements
on: [workflow_call]
jobs:
  install_reqs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Requirements
        run: |
          pip list
          pip install --upgrade pip
          pip install -r requirements.txt
