name: test-workflow
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v4
      - name: Setup Checkout (external)
        uses: actions/checkout@v4
        with:
          repository: SmartDCSITlimited/test-event-generator
          ref: CDSDT-41-test-event-generator
          # token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: external
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Requirements
        run: |
          echo "Installing absolutely nothing for now!"
          pip install --upgrade pip
          pip install pytest
          pytest --version
          pip install flake8
          flake8 --version
          pip install -r requirements.txt
          # ./ci/install_prerequisites.sh
      - name: Run Tests
        run: |
          echo "Hello World!"
          # export PYTHONPATH=/workspaces/test-harness:$PYTHONPATH
          # pytest --junitxml=report.xml --ignore=tests/test_harness/pv_config/test_pv_config_generation.py
          #   --ignore=tests/test_harness/process_manager/test_send_job_defs.py
          #   --ignore=tests/test_harness/process_manager/test_process_manager__init__.py
          #   --ignore=tests/test_harness/process_manager/test_generate_test_files.py
          #   --ignore=tests/test_harness/process_manager/test_tests.py
          #   --ignore=tests/test_harness/process_manager/test_calc_pv_finish.py
