name: test-workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      'main'
jobs:
  sast:
    uses: SmartDCSITlimited/actions-store/.github/workflows/SAST.yml@main
  secret-detection:
    uses: SmartDCSITlimited/actions-store/.github/workflows/SecretDetection.yml@main
  python-linting:
    uses: SmartDCSITlimited/actions-store/.github/workflows/PythonLinting.yml@main

  run-tests:
    if: |
        github.repository == 'SmartDCSITlimited/test-harness'
            && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v4

      - name: Setup Checkout (external)
        uses: actions/checkout@v4
        with:
          repository: SmartDCSITlimited/test-event-generator
          ssh-key: ${{ secrets.TESTKEY }}
          path: external

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Requirements
        run: |
          pip install --upgrade pip

          pip install pytest
          pytest --version

          pip install -r requirements.txt

      - name: Install Requirements (external)
        run: |
          cd external
          pip install -r requirements.txt
          pip install .
          cd ..
          rm -rf external

      - name: Run Tests
        run: |
          export PYTHONPATH=/workspaces/test-harness:$PYTHONPATH
          pytest 